version: '3.3'
services:
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'critter'
            MYSQL_USER: 'critter'
            MYSQL_PASSWORD: 'critter'
            MYSQL_ROOT_PASSWORD: 'critter'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - critter_volume:/var/lib/mysql
volumes:
    critter_volume: